### ISSUE TITLE
lvSystem::IsPausingLowerScripts lvfunction is missing in Commands.xml

### ISSUE THREAD

**Issue by yu-tang** [SoulEngineProject/Light.vn-config#31]
User wiki has its own description.
https://wikiwiki.jp/lightvn/funcs.html#lvSystem_IsPausingLowerScripts
But the official information is missing.

**Comment by hsdk123** [comment]
@TakashiYukihara 
`lvSystem::IsPausingLowerScripts` に関した情報がWikiのどこかに残っておりますか？

**Comment by TakashiYukihara** [comment]
[](https://wikiwiki.jp/lightvn/funcs#lvSystem_IsPausingLowerScripts)
「.html」が不要ですね。

**Comment by yu-tang** [comment]
「.html」は不要でした。ありがとうございます。
初学者なのでよく分からないのですが、これは載せるべきではない関数ですか？
もしそうであれば、issueはクローズしますが。

**Comment by hsdk123** [comment]
https://github.com/SoulEngineProject/Light.vn-config/pull/33 にて修正完了
